name: MWE CI Orchestrator

permissions:
  contents: read

on:
  pull_request:
  workflow_dispatch:

jobs:
  setup:
    name: Setup
    uses: ./.github/workflows/setup-mwe.yml
    with:
      node-version: "24"

  lint:
    name: Lint
    needs: setup
    uses: ./.github/workflows/lint-mwe-codebase.yml
    with:
      node-version: "24"
      allow-fail: false

  build:
    name: Build
    needs: lint
    uses: ./.github/workflows/build-mwe-packages.yml
    with:
      node-version: "24"

  test-e2e-web:
    name: E2E Web
    needs: build
    uses: ./.github/workflows/test-mwe-e2e-web.yml
    with:
      node-version: "24"
      allow-fail: true
