name: MWE Container Publish

permissions:
  contents: read
  packages: write

on:
  pull_request:
    branches:
      - releases/*
  workflow_dispatch:
  workflow_call:
    inputs:
      node-version:
        required: false
        type: string
        description: Node.js Version
        default: "24"
      allow-fail:
        required: false
        type: boolean
        description: Allow workflow to fail
        default: false

jobs:
  publish-containers:
    name: Publish MWE Containers
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Restore Yarn cache
        uses: actions/cache@v4
        with:
          path: |
            .yarn/cache
            .pnp.cjs
            .yarn/install-state.gz
          key: node-${{ runner.os }}-node-${{ inputs.node-version }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            node-${{ runner.os }}-node-${{ inputs.node-version }}-yarn-
